### ISSUE TITLE
Flutter Web - XMLHttpRequest error

### ISSUE THREAD

**Issue by apps-auth** [Dammyololade/flutter_polyline_points#20]
Hello, I am getting the following CORS error on the web flutter: Error: XMLHttpRequest error.
Any way to solve this problem?

**Comment by ravipatelxongolab** [comment]
I am also face this error. can you help me?
`flutter: Error: XMLHttpRequest error.`

**Comment by brandonwatkins** [comment]
I am also facing this error 👎 Any help would be appreciated

**Comment by lokijuy** [comment]
did anyone solved this error? 
Please help me with this problem. Thank you.

**Comment by buimanhhungit** [comment]
Me too. Pls add CORS in you api.

**Comment by aaqibism** [comment]
I'm assuming this is intended behavior because of the inherent security issues of calling APIs client side. One solution would be to set up within your google cloud project a cloud function that is public and sends an http request to the API and return the results to the client. If you're already using firebase in your project, you could use its version of cloud functions.

**Comment by apps-auth** [comment]
> I'm assuming this is intended behavior because of the inherent security issues of calling APIs client side. One solution would be to set up within your google cloud project a cloud function that is public and sends an http request to the API and return the results to the client. If you're already using firebase in your project, you could use its version of cloud functions.

Yes, that's exactly how I solved this problem. I made the calls through my server
